List<Map<String, String>> countriesEnglish = [
  {"name": 'None', "dial_code": "", "code": "", "value": "-1"},
  {"name": "Afghanistan", "dial_code": "+93", "code": "AF", "value": "1"},
  {"name": "Aland Islands", "dial_code": "+358", "code": "AX", "value": "2"},
  {"name": "Albania", "dial_code": "+355", "code": "AL", "value": "3"},
  {"name": "Algeria", "dial_code": "+213", "code": "DZ", "value": "4"},
  {"name": "AmericanSamoa", "dial_code": "+1684", "code": "AS", "value": "5"},
  {"name": "Andorra", "dial_code": "+376", "code": "AD", "value": "6"},
  {"name": "Angola", "dial_code": "+244", "code": "AO", "value": "7"},
  {"name": "Anguilla", "dial_code": "+1264", "code": "AI", "value": "8"},
  {"name": "Antarctica", "dial_code": "+672", "code": "AQ", "value": "9"},
  {
    "name": "Antigua and Barbuda",
    "dial_code": "+1268",
    "code": "AG",
    "value": "10"
  },
  {"name": "Argentina", "dial_code": "+54", "code": "AR", "value": "11"},
  {"name": "Armenia", "dial_code": "+374", "code": "AM", "value": "12"},
  {"name": "Aruba", "dial_code": "+297", "code": "AW", "value": "13"},
  {"name": "Australia", "dial_code": "+61", "code": "AU", "value": "14"},
  {"name": "Austria", "dial_code": "+43", "code": "AT", "value": "15"},
  {"name": "Azerbaijan", "dial_code": "+994", "code": "AZ", "value": "16"},
  {"name": "Bahamas", "dial_code": "+1242", "code": "BS", "value": "17"},
  {"name": "Bahrain", "dial_code": "+973", "code": "BH", "value": "18"},
  {"name": "Bangladesh", "dial_code": "+880", "code": "BD", "value": "19"},
  {"name": "Barbados", "dial_code": "+1246", "code": "BB", "value": "20"},
  {"name": "Belarus", "dial_code": "+375", "code": "BY", "value": "21"},
  {"name": "Belgium", "dial_code": "+32", "code": "BE", "value": "22"},
  {"name": "Belize", "dial_code": "+501", "code": "BZ", "value": "23"},
  {"name": "Benin", "dial_code": "+229", "code": "BJ", "value": "24"},
  {"name": "Bermuda", "dial_code": "+1441", "code": "BM", "value": "25"},
  {"name": "Bhutan", "dial_code": "+975", "code": "BT", "value": "26"},
  {
    "name": "Bolivia, Plurinational State of",
    "dial_code": "+591",
    "code": "BO",
    "value": "27"
  },
  {
    "name": "Bosnia and Herzegovina",
    "dial_code": "+387",
    "code": "BA",
    "value": "28"
  },
  {"name": "Botswana", "dial_code": "+267", "code": "BW", "value": "28"},
  {"name": "Brazil", "dial_code": "+55", "code": "BR", "value": "29"},
  {
    "name": "British Indian Ocean Territory",
    "dial_code": "+246",
    "code": "IO",
    "value": "30"
  },
  {
    "name": "Brunei Darussalam",
    "dial_code": "+673",
    "code": "BN",
    "value": "31"
  },
  {"name": "Bulgaria", "dial_code": "+359", "code": "BG", "value": "32"},
  {"name": "Burkina Faso", "dial_code": "+226", "code": "BF", "value": "33"},
  {"name": "Burundi", "dial_code": "+257", "code": "BI", "value": "34"},
  {"name": "Cambodia", "dial_code": "+855", "code": "KH", "value": "35"},
  {"name": "Cameroon", "dial_code": "+237", "code": "CM", "value": "36"},
  {"name": "Canada", "dial_code": "+1", "code": "CA", "value": "37"},
  {"name": "Cape Verde", "dial_code": "+238", "code": "CV", "value": "38"},
  {"name": "Cayman Islands", "dial_code": "+ 345", "code": "KY", "value": "39"},
  {
    "name": "Central African Republic",
    "dial_code": "+236",
    "code": "CF",
    "value": "40"
  },
  {"name": "Chad", "dial_code": "+235", "code": "TD", "value": "41"},
  {"name": "Chile", "dial_code": "+56", "code": "CL", "value": "42"},
  {"name": "China", "dial_code": "+86", "code": "CN", "value": "43"},
  {"name": "Christmas Island", "dial_code": "+61", "code": "CX", "value": "44"},
  {
    "name": "Cocos (Keeling) Islands",
    "dial_code": "+61",
    "code": "CC",
    "value": "45"
  },
  {"name": "Colombia", "dial_code": "+57", "code": "CO", "value": "46"},
  {"name": "Comoros", "dial_code": "+269", "code": "KM", "value": "47"},
  {"name": "Congo", "dial_code": "+242", "code": "CG", "value": "48"},
  {
    "name": "Congo, The Democratic Republic of the Congo",
    "dial_code": "+243",
    "code": "CD",
    "value": "49"
  },
  {"name": "Cook Islands", "dial_code": "+682", "code": "CK", "value": "50"},
  {"name": "Costa Rica", "dial_code": "+506", "code": "CR", "value": "51"},
  {"name": "Cote d'Ivoire", "dial_code": "+225", "code": "CI", "value": "52"},
  {"name": "Croatia", "dial_code": "+385", "code": "HR", "value": "53"},
  {"name": "Cuba", "dial_code": "+53", "code": "CU", "value": "54"},
  {"name": "Cyprus", "dial_code": "+357", "code": "CY", "value": "55"},
  {"name": "Czech Republic", "dial_code": "+420", "code": "CZ", "value": "55"},
  {"name": "Denmark", "dial_code": "+45", "code": "DK", "value": "56"},
  {"name": "Djibouti", "dial_code": "+253", "code": "DJ", "value": "57"},
  {"name": "Dominica", "dial_code": "+1767", "code": "DM", "value": "58"},
  {
    "name": "Dominican Republic",
    "dial_code": "+1849",
    "code": "DO",
    "value": "59"
  },
  {"name": "Ecuador", "dial_code": "+593", "code": "EC", "value": "60"},
  {"name": "Egypt", "dial_code": "+20", "code": "EG", "value": "61"},
  {"name": "El Salvador", "dial_code": "+503", "code": "SV", "value": "62"},
  {
    "name": "Equatorial Guinea",
    "dial_code": "+240",
    "code": "GQ",
    "value": "63"
  },
  {"name": "Eritrea", "dial_code": "+291", "code": "ER", "value": "64"},
  {"name": "Estonia", "dial_code": "+372", "code": "EE", "value": "65"},
  {"name": "Ethiopia", "dial_code": "+251", "code": "ET", "value": "66"},
  {
    "name": "Falkland Islands (Malvinas)",
    "dial_code": "+500",
    "code": "FK",
    "value": "67"
  },
  {"name": "Faroe Islands", "dial_code": "+298", "code": "FO", "value": "68"},
  {"name": "Fiji", "dial_code": "+679", "code": "FJ", "value": "69"},
  {"name": "Finland", "dial_code": "+358", "code": "FI", "value": "70"},
  {"name": "France", "dial_code": "+33", "code": "FR", "value": "71"},
  {"name": "French Guiana", "dial_code": "+594", "code": "GF", "value": "72"},
  {
    "name": "French Polynesia",
    "dial_code": "+689",
    "code": "PF",
    "value": "73"
  },
  {"name": "Gabon", "dial_code": "+241", "code": "GA", "value": "74"},
  {"name": "Gambia", "dial_code": "+220", "code": "GM", "value": "75"},
  {"name": "Georgia", "dial_code": "+995", "code": "GE", "value": "76"},
  {"name": "Germany", "dial_code": "+49", "code": "DE", "value": "77"},
  {"name": "Ghana", "dial_code": "+233", "code": "GH", "value": "78"},
  {"name": "Gibraltar", "dial_code": "+350", "code": "GI", "value": "79"},
  {"name": "Greece", "dial_code": "+30", "code": "GR", "value": "80"},
  {"name": "Greenland", "dial_code": "+299", "code": "GL", "value": "81"},
  {"name": "Grenada", "dial_code": "+1473", "code": "GD", "value": "82"},
  {"name": "Guadeloupe", "dial_code": "+590", "code": "GP", "value": "83"},
  {"name": "Guam", "dial_code": "+1671", "code": "GU", "value": "84"},
  {"name": "Guatemala", "dial_code": "+502", "code": "GT", "value": "85"},
  {"name": "Guernsey", "dial_code": "+44", "code": "GG", "value": "86"},
  {"name": "Guinea", "dial_code": "+224", "code": "GN", "value": "87"},
  {"name": "Guinea-Bissau", "dial_code": "+245", "code": "GW", "value": "88"},
  {"name": "Guyana", "dial_code": "+595", "code": "GY", "value": "89"},
  {"name": "Haiti", "dial_code": "+509", "code": "HT", "value": "90"},
  {
    "name": "Holy See (Vatican City State)",
    "dial_code": "+379",
    "code": "VA",
    "value": "91"
  },
  {"name": "Honduras", "dial_code": "+504", "code": "HN", "value": "92"},
  {"name": "Hong Kong", "dial_code": "+852", "code": "HK", "value": "93"},
  {"name": "Hungary", "dial_code": "+36", "code": "HU", "value": "94"},
  {"name": "Iceland", "dial_code": "+354", "code": "IS", "value": "95"},
  {"name": "India", "dial_code": "+91", "code": "IN", "value": "96"},
  {"name": "Indonesia", "dial_code": "+62", "code": "ID", "value": "97"},
  {
    "name": "Iran, Islamic Republic of Persian Gulf",
    "dial_code": "+98",
    "code": "IR",
    "value": "98"
  },
  {"name": "Iraq", "dial_code": "+964", "code": "IQ", "value": "99"},
  {"name": "Ireland", "dial_code": "+353", "code": "IE", "value": "100"},
  {"name": "Isle of Man", "dial_code": "+44", "code": "IM", "value": "101"},
  {"name": "Israel", "dial_code": "+972", "code": "IL", "value": "102"},
  {"name": "Italy", "dial_code": "+39", "code": "IT", "value": "103"},
  {"name": "Jamaica", "dial_code": "+1876", "code": "JM", "value": "104"},
  {"name": "Japan", "dial_code": "+81", "code": "JP", "value": "105"},
  {"name": "Jersey", "dial_code": "+44", "code": "JE", "value": "106"},
  {"name": "Jordan", "dial_code": "+962", "code": "JO", "value": "107"},
  {"name": "Kazakhstan", "dial_code": "+77", "code": "KZ", "value": "108"},
  {"name": "Kenya", "dial_code": "+254", "code": "KE", "value": "109"},
  {"name": "Kiribati", "dial_code": "+686", "code": "KI", "value": "110"},
  {
    "name": "Korea, Democratic People's Republic of Korea",
    "dial_code": "+850",
    "code": "KP",
    "value": "111"
  },
  {
    "name": "Korea, Republic of South Korea",
    "dial_code": "+82",
    "code": "KR",
    "value": "112"
  },
  {"name": "Kuwait", "dial_code": "+965", "code": "KW", "value": "113"},
  {"name": "Kyrgyzstan", "dial_code": "+996", "code": "KG", "value": "114"},
  {"name": "Laos", "dial_code": "+856", "code": "LA", "value": "115"},
  {"name": "Latvia", "dial_code": "+371", "code": "LV", "value": "116"},
  {"name": "Lebanon", "dial_code": "+961", "code": "LB", "value": "117"},
  {"name": "Lesotho", "dial_code": "+266", "code": "LS", "value": "118"},
  {"name": "Liberia", "dial_code": "+231", "code": "LR", "value": "119"},
  {
    "name": "Libyan Arab Jamahiriya",
    "dial_code": "+218",
    "code": "LY",
    "value": "120"
  },
  {"name": "Liechtenstein", "dial_code": "+423", "code": "LI", "value": "121"},
  {"name": "Lithuania", "dial_code": "+370", "code": "LT", "value": "122"},
  {"name": "Luxembourg", "dial_code": "+352", "code": "LU", "value": "123"},
  {"name": "Macao", "dial_code": "+853", "code": "MO", "value": "124"},
  {"name": "Macedonia", "dial_code": "+389", "code": "MK", "value": "125"},
  {"name": "Madagascar", "dial_code": "+261", "code": "MG", "value": "126"},
  {"name": "Malawi", "dial_code": "+265", "code": "MW", "value": "127"},
  {"name": "Malaysia", "dial_code": "+60", "code": "MY", "value": "128"},
  {"name": "Maldives", "dial_code": "+960", "code": "MV", "value": "129"},
  {"name": "Mali", "dial_code": "+223", "code": "ML", "value": "130"},
  {"name": "Malta", "dial_code": "+356", "code": "MT", "value": "131"},
  {
    "name": "Marshall Islands",
    "dial_code": "+692",
    "code": "MH",
    "value": "132"
  },
  {"name": "Martinique", "dial_code": "+596", "code": "MQ", "value": "133"},
  {"name": "Mauritania", "dial_code": "+222", "code": "MR", "value": "134"},
  {"name": "Mauritius", "dial_code": "+230", "code": "MU", "value": "135"},
  {"name": "Mayotte", "dial_code": "+262", "code": "YT", "value": "136"},
  {"name": "Mexico", "dial_code": "+52", "code": "MX", "value": "137"},
  {
    "name": "Micronesia, Federated States of Micronesia",
    "dial_code": "+691",
    "code": "FM",
    "value": "138"
  },
  {"name": "Moldova", "dial_code": "+373", "code": "MD", "value": "139"},
  {"name": "Monaco", "dial_code": "+377", "code": "MC", "value": "140"},
  {"name": "Mongolia", "dial_code": "+976", "code": "MN", "value": "141"},
  {"name": "Montenegro", "dial_code": "+382", "code": "ME", "value": "142"},
  {"name": "Montserrat", "dial_code": "+1664", "code": "MS", "value": "143"},
  {"name": "Morocco", "dial_code": "+212", "code": "MA", "value": "144"},
  {"name": "Mozambique", "dial_code": "+258", "code": "MZ", "value": "145"},
  {"name": "Myanmar", "dial_code": "+95", "code": "MM", "value": "146"},
  {"name": "Namibia", "dial_code": "+264", "code": "NA", "value": "147"},
  {"name": "Nauru", "dial_code": "+674", "code": "NR", "value": "148"},
  {"name": "Nepal", "dial_code": "+977", "code": "NP", "value": "149"},
  {"name": "Netherlands", "dial_code": "+31", "code": "NL", "value": "150"},
  {
    "name": "Netherlands Antilles",
    "dial_code": "+599",
    "code": "AN",
    "value": "151"
  },
  {"name": "New Caledonia", "dial_code": "+687", "code": "NC", "value": "152"},
  {"name": "New Zealand", "dial_code": "+64", "code": "NZ", "value": "153"},
  {"name": "Nicaragua", "dial_code": "+505", "code": "NI", "value": "154"},
  {"name": "Niger", "dial_code": "+227", "code": "NE", "value": "155"},
  {"name": "Nigeria", "dial_code": "+234", "code": "NG", "value": "156"},
  {"name": "Niue", "dial_code": "+683", "code": "NU", "value": "157"},
  {"name": "Norfolk Island", "dial_code": "+672", "code": "NF", "value": "158"},
  {
    "name": "Northern Mariana Islands",
    "dial_code": "+1670",
    "code": "MP",
    "value": "159"
  },
  {"name": "Norway", "dial_code": "+47", "code": "NO", "value": "160"},
  {"name": "Oman", "dial_code": "+968", "code": "OM", "value": "161"},
  {"name": "Pakistan", "dial_code": "+92", "code": "PK", "value": "162"},
  {"name": "Palau", "dial_code": "+680", "code": "PW", "value": "163"},
  {
    "name": "Palestinian Territory, Occupied",
    "dial_code": "+970",
    "code": "PS",
    "value": "164"
  },
  {"name": "Panama", "dial_code": "+507", "code": "PA", "value": "165"},
  {
    "name": "Papua New Guinea",
    "dial_code": "+675",
    "code": "PG",
    "value": "166"
  },
  {"name": "Paraguay", "dial_code": "+595", "code": "PY", "value": "167"},
  {"name": "Peru", "dial_code": "+51", "code": "PE", "value": "168"},
  {"name": "Philippines", "dial_code": "+63", "code": "PH", "value": "169"},
  {"name": "Pitcairn", "dial_code": "+872", "code": "PN", "value": "170"},
  {"name": "Poland", "dial_code": "+48", "code": "PL", "value": "171"},
  {"name": "Portugal", "dial_code": "+351", "code": "PT", "value": "172"},
  {"name": "Puerto Rico", "dial_code": "+1939", "code": "PR", "value": "173"},
  {"name": "Qatar", "dial_code": "+974", "code": "QA", "value": "174"},
  {"name": "Romania", "dial_code": "+40", "code": "RO", "value": "175"},
  {"name": "Russia", "dial_code": "+7", "code": "RU", "value": "176"},
  {"name": "Rwanda", "dial_code": "+250", "code": "RW", "value": "177"},
  {"name": "Reunion", "dial_code": "+262", "code": "RE", "value": "178"},
  {
    "name": "Saint Barthelemy",
    "dial_code": "+590",
    "code": "BL",
    "value": "179"
  },
  {
    "name": "Saint Helena, Ascension and Tristan Da Cunha",
    "dial_code": "+290",
    "code": "SH",
    "value": "180"
  },
  {
    "name": "Saint Kitts and Nevis",
    "dial_code": "+1869",
    "code": "KN",
    "value": "181"
  },
  {"name": "Saint Lucia", "dial_code": "+1758", "code": "LC", "value": "182"},
];
